apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: poc-camel
  labels:
    app: poc-camel
    component: config
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  CAMEL_COMPONENT_KAFKA_BROKERS: "kafka:29092"
  PROVIDER_A_URL: "http://payment-processor:8080/provider-a/process"
  PROVIDER_B_URL: "http://payment-processor:8080/provider-b/process"
  DATABASE_URL: "jdbc:postgresql://postgres:5432/payments"
  POSTGRES_DB: "payments"
  DB_USER: "payments"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-rules-config
  namespace: poc-camel
  labels:
    app: poc-camel
    component: config
data:
  fraud.rules.high-amount-threshold: "15000"
  fraud.rules.high-risk-countries: "XX,YY,ZZ"
  fraud.rules.rapid-retry-threshold: "3"
  fraud.rules.new-method-days-threshold: "30"
  fraud.rules.unusual-hour-start: "2"
  fraud.rules.unusual-hour-end: "5"
  fraud.rules.max-risk-score: "100"