apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: poc-camel
  labels:
    app: poc-camel
    component: tracing
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"