apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: poc-camel
  labels:
    app: api-gateway
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: payment-processor
  namespace: poc-camel
  labels:
    app: payment-processor
    component: processor
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: payment-processor
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-external
  namespace: poc-camel
  labels:
    app: api-gateway
    component: backend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app: api-gateway