# HTTP Server
quarkus.http.port=8080

# OpenAPI / Swagger
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Health Check
quarkus.smallrye-health.root-path=/health
quarkus.smallrye-health.liveness-path=/health/live
quarkus.smallrye-health.readiness-path=/health/ready
quarkus.smallrye-health.startup-path=/health/started

# Application
quarkus.application.name=payment-gateway

# CORS (development)
quarkus.http.cors=true
quarkus.http.cors.origins=*

# Kafka
kafka.bootstrap.servers=localhost:9092
kafka.topic.payments.received=payments.events.received

# Camel Kafka
camel.component.kafka.brokers=${kafka.bootstrap.servers}

# Logging
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p traceId=%X{traceId} %s%e%n